name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Terraform Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check

  deploy:
    name: Deploy Terraform Infrastructure
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          managed_identity: true

      # Deploy to Development Environment
      - name: Terraform Init for Dev
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_DEV }}" \
                            -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME_DEV }}" \
                            -backend-config="key=terraform-dev.tfstate"

      - name: Terraform Plan for Dev
        run: terraform plan -var-file="environments/dev.tfvars" -out=tfplan-dev

      - name: Terraform Apply for Dev
        run: terraform apply -auto-approve tfplan-dev

      # Deploy to Test Environment
      - name: Terraform Init for Test
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_TEST }}" \
                            -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME_TEST }}" \
                            -backend-config="key=terraform-test.tfstate"

      - name: Terraform Plan for Test
        run: terraform plan -var-file="environments/test.tfvars" -out=tfplan-test

      - name: Terraform Apply for Test
        run: terraform apply -auto-approve tfplan-test

      # Deploy to Production Environment
      - name: Terraform Init for Prod
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_PROD }}" \
                            -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME_PROD }}" \
                            -backend-config="key=terraform-prod.tfstate"

      - name: Terraform Plan for Prod
        run: terraform plan -var-file="environments/prod.tfvars" -out=tfplan-prod

      - name: Terraform Apply for Prod
        run: terraform apply -auto-approve tfplan-prod